-- Auto-generated EZ Hud theme export
return {
    ezcastbar = {
        enable = true,
        fade_duration = 0.8,
        image_bar = "gui/ezcastbar/ezcastbar_bar.png",
        image_frame = "gui/ezcastbar/ezcastbar_bg.png",
        offset = {
            x = 0,
            y = 0,
        },
        scale = 1,
        size = {
            height = 13,
            width = 350,
        },
    },
    ezmount = {
        enable = true,
        name = "Raptor",
    },
    ezparty = {
        buffs = {
            enable = true,
            global_scale = 1,
            member = {
                horizontal_limit = 10,
                location = "below",
                offset = {
                    x = 0,
                    y = 0,
                },
                scale = 1,
                vertical_limit = 2,
            },
            player = {
                horizontal_limit = 10,
                location = "below",
                offset = {
                    x = 0,
                    y = 0,
                },
                scale = 1,
                vertical_limit = 2,
            },
        },
        enable = true,
        gui_profiles = {
            member = {
                hp_bar = {
                    color = {
                        alpha = 255,
                        blue = 255,
                        green = 255,
                        red = 255,
                    },
                    offset = {
                        x = 48,
                        y = 68,
                    },
                    size = {
                        height = 23,
                        width = 180,
                    },
                    texture = "gui/ezparty/HP_bar.png",
                    type = "image",
                },
                hp_label = {
                    bold = false,
                    bottom = false,
                    color = {
                        alpha = 220,
                        blue = 255,
                        green = 255,
                        red = 255,
                    },
                    font = "Arial",
                    italic = true,
                    offset = {
                        x = 50,
                        y = 82,
                    },
                    right = false,
                    size = 14,
                    stroke = {
                        alpha = 180,
                        blue = 0,
                        green = 0,
                        red = 0,
                        width = 1,
                    },
                    type = "text",
                },
                hp_value = {
                    bold = true,
                    bottom = false,
                    color = {
                        alpha = 255,
                        blue = 255,
                        green = 255,
                        red = 255,
                    },
                    font = "Arial",
                    italic = false,
                    offset = {
                        x = 176,
                        y = 82,
                    },
                    right = false,
                    size = 16,
                    stroke = {
                        alpha = 200,
                        blue = 0,
                        green = 0,
                        red = 0,
                        width = 1,
                    },
                    type = "text",
                },
                hpp = {
                    bold = true,
                    bottom = false,
                    color = {
                        alpha = 255,
                        blue = 0,
                        green = 215,
                        red = 230,
                    },
                    font = "Arial",
                    italic = false,
                    offset = {
                        x = 290,
                        y = 25,
                    },
                    right = false,
                    size = 20,
                    stroke = {
                        alpha = 220,
                        blue = 0,
                        green = 0,
                        red = 0,
                        width = 2,
                    },
                    type = "text",
                },
                mp_bar = {
                    color = {
                        alpha = 255,
                        blue = 255,
                        green = 255,
                        red = 255,
                    },
                    offset = {
                        x = 236,
                        y = 68,
                    },
                    size = {
                        height = 23,
                        width = 180,
                    },
                    texture = "gui/ezparty/MP_bar.png",
                    type = "image",
                },
                mp_label = {
                    bold = false,
                    bottom = false,
                    color = {
                        alpha = 220,
                        blue = 255,
                        green = 255,
                        red = 255,
                    },
                    font = "Arial",
                    italic = true,
                    offset = {
                        x = 241,
                        y = 82,
                    },
                    right = false,
                    size = 14,
                    stroke = {
                        alpha = 180,
                        blue = 0,
                        green = 0,
                        red = 0,
                        width = 1,
                    },
                    type = "text",
                },
                mp_value = {
                    bold = true,
                    bottom = false,
                    color = {
                        alpha = 255,
                        blue = 255,
                        green = 220,
                        red = 200,
                    },
                    font = "Arial",
                    italic = false,
                    offset = {
                        x = 366,
                        y = 82,
                    },
                    right = false,
                    size = 16,
                    stroke = {
                        alpha = 200,
                        blue = 0,
                        green = 0,
                        red = 0,
                        width = 1,
                    },
                    type = "text",
                },
                name = {
                    bold = true,
                    bottom = false,
                    color = {
                        alpha = 255,
                        blue = 255,
                        green = 255,
                        red = 255,
                    },
                    font = "Arial",
                    italic = false,
                    offset = {
                        x = 49,
                        y = 26,
                    },
                    right = false,
                    size = 20,
                    stroke = {
                        alpha = 220,
                        blue = 0,
                        green = 0,
                        red = 0,
                        width = 2,
                    },
                    type = "text",
                },
                tp_bar = {
                    color = {
                        alpha = 255,
                        blue = 255,
                        green = 255,
                        red = 255,
                    },
                    offset = {
                        x = 427,
                        y = 68,
                    },
                    size = {
                        height = 23,
                        width = 180,
                    },
                    texture = "gui/ezparty/TP_bar.png",
                    type = "image",
                },
                tp_label = {
                    bold = false,
                    bottom = false,
                    color = {
                        alpha = 220,
                        blue = 255,
                        green = 255,
                        red = 255,
                    },
                    font = "Arial",
                    italic = true,
                    offset = {
                        x = 431,
                        y = 82,
                    },
                    right = false,
                    size = 14,
                    stroke = {
                        alpha = 180,
                        blue = 0,
                        green = 0,
                        red = 0,
                        width = 1,
                    },
                    type = "text",
                },
                tp_value = {
                    bold = true,
                    bottom = false,
                    color = {
                        alpha = 255,
                        blue = 255,
                        green = 255,
                        red = 255,
                    },
                    font = "Arial",
                    italic = false,
                    offset = {
                        x = 557,
                        y = 82,
                    },
                    right = false,
                    size = 16,
                    stroke = {
                        alpha = 200,
                        blue = 0,
                        green = 0,
                        red = 0,
                        width = 1,
                    },
                    type = "text",
                },
            },
            player = {
                hp_bar = {
                    color = {
                        alpha = 255,
                        blue = 255,
                        green = 255,
                        red = 255,
                    },
                    offset = {
                        x = 137,
                        y = 87,
                    },
                    size = {
                        height = 25,
                        width = 178,
                    },
                    texture = "gui/ezparty/HP_bar.png",
                    type = "image",
                },
                hp_label = {
                    bold = false,
                    bottom = false,
                    color = {
                        alpha = 220,
                        blue = 255,
                        green = 255,
                        red = 255,
                    },
                    font = "Arial",
                    italic = true,
                    offset = {
                        x = 150,
                        y = 68,
                    },
                    right = false,
                    size = 14,
                    stroke = {
                        alpha = 180,
                        blue = 0,
                        green = 0,
                        red = 0,
                        width = 1,
                    },
                    type = "text",
                },
                hp_value = {
                    bold = true,
                    bottom = false,
                    color = {
                        alpha = 255,
                        blue = 0,
                        green = 215,
                        red = 255,
                    },
                    font = "Arial",
                    italic = false,
                    offset = {
                        x = 222,
                        y = 68,
                    },
                    right = false,
                    size = 16,
                    stroke = {
                        alpha = 200,
                        blue = 0,
                        green = 0,
                        red = 0,
                        width = 1,
                    },
                    type = "text",
                },
                hpp = {
                    bold = true,
                    bottom = false,
                    color = {
                        alpha = 255,
                        blue = 0,
                        green = 215,
                        red = 230,
                    },
                    font = "Arial",
                    italic = false,
                    offset = {
                        x = 357,
                        y = 32,
                    },
                    right = false,
                    size = 20,
                    stroke = {
                        alpha = 220,
                        blue = 0,
                        green = 0,
                        red = 0,
                        width = 2,
                    },
                    type = "text",
                },
                mp_bar = {
                    color = {
                        alpha = 255,
                        blue = 255,
                        green = 255,
                        red = 255,
                    },
                    offset = {
                        x = 334,
                        y = 87,
                    },
                    size = {
                        height = 25,
                        width = 178,
                    },
                    texture = "gui/ezparty/MP_bar.png",
                    type = "image",
                },
                mp_label = {
                    bold = false,
                    bottom = false,
                    color = {
                        alpha = 220,
                        blue = 255,
                        green = 255,
                        red = 255,
                    },
                    font = "Arial",
                    italic = true,
                    offset = {
                        x = 320,
                        y = 68,
                    },
                    right = false,
                    size = 14,
                    stroke = {
                        alpha = 180,
                        blue = 0,
                        green = 0,
                        red = 0,
                        width = 1,
                    },
                    type = "text",
                },
                mp_value = {
                    bold = true,
                    bottom = false,
                    color = {
                        alpha = 255,
                        blue = 255,
                        green = 220,
                        red = 200,
                    },
                    font = "Arial",
                    italic = false,
                    offset = {
                        x = 392,
                        y = 68,
                    },
                    right = false,
                    size = 16,
                    stroke = {
                        alpha = 200,
                        blue = 0,
                        green = 0,
                        red = 0,
                        width = 1,
                    },
                    type = "text",
                },
                name = {
                    bold = true,
                    bottom = false,
                    color = {
                        alpha = 255,
                        blue = 255,
                        green = 255,
                        red = 255,
                    },
                    font = "Arial",
                    italic = false,
                    offset = {
                        x = 149,
                        y = 30,
                    },
                    right = false,
                    size = 20,
                    stroke = {
                        alpha = 220,
                        blue = 0,
                        green = 0,
                        red = 0,
                        width = 2,
                    },
                    type = "text",
                },
                tp_bar = {
                    color = {
                        alpha = 255,
                        blue = 255,
                        green = 255,
                        red = 255,
                    },
                    offset = {
                        x = 455,
                        y = 96,
                    },
                    size = {
                        height = 30,
                        width = 438,
                    },
                    texture = "gui/ezparty/TP_bar.png",
                    type = "image",
                },
                tp_label = {
                    bold = false,
                    bottom = false,
                    color = {
                        alpha = 220,
                        blue = 255,
                        green = 255,
                        red = 255,
                    },
                    font = "Arial",
                    italic = true,
                    offset = {
                        x = 490,
                        y = 68,
                    },
                    right = false,
                    size = 14,
                    stroke = {
                        alpha = 180,
                        blue = 0,
                        green = 0,
                        red = 0,
                        width = 1,
                    },
                    type = "text",
                },
                tp_value = {
                    bold = true,
                    bottom = false,
                    color = {
                        alpha = 255,
                        blue = 255,
                        green = 255,
                        red = 255,
                    },
                    font = "Arial",
                    italic = false,
                    offset = {
                        x = 560,
                        y = 68,
                    },
                    right = false,
                    size = 16,
                    stroke = {
                        alpha = 200,
                        blue = 0,
                        green = 0,
                        red = 0,
                        width = 1,
                    },
                    type = "text",
                },
            },
        },
        layout = {
            draggable = false,
            vertical_spacing = 32,
        },
        member_frame = {
            color = {
                alpha = 255,
                blue = 255,
                green = 255,
                red = 255,
            },
            draggable = false,
            enable = true,
            linked = true,
            offset = {
                x = 100,
                y = 0,
            },
            pos = {
                x = 0.83230088495575,
                y = 0.62307692307692,
            },
            repeatable = {
                x = 1,
                y = 1,
            },
            size = {
                height = 131,
                width = 631,
            },
            texture = {
                fit = false,
                path = "gui/ezparty/member_frame.png",
            },
            visible = false,
        },
        player_frame = {
            linked = true,
            one = {
                color = {
                    alpha = 255,
                    blue = 255,
                    green = 255,
                    red = 255,
                },
                draggable = false,
                enable = false,
                pos = {
                    x = 0,
                    y = 0,
                },
                repeatable = {
                    x = 1,
                    y = 1,
                },
                size = {
                    height = 150,
                    width = 730,
                },
                texture = {
                    fit = false,
                    path = "gui/ezparty/player_frame.png",
                },
                visible = false,
            },
            two = {
                color = {
                    alpha = 255,
                    blue = 255,
                    green = 255,
                    red = 255,
                },
                draggable = false,
                enable = true,
                pos = {
                    x = 0.40309734513274,
                    y = 0.76692307692308,
                },
                repeatable = {
                    x = 1,
                    y = 1,
                },
                size = {
                    height = 150,
                    width = 730,
                },
                texture = {
                    fit = false,
                    path = "gui/ezparty/player_frame.png",
                },
                visible = false,
            },
            unique = true,
        },
        scale = 0.6,
        target_frame = {
            above_member_frames = {
                enable = false,
                offset = {
                    x = 0,
                    y = -10,
                },
            },
            enable = true,
            image = "gui/ezparty/target_frame.png",
            size = {
                height = 339,
                width = 1649,
            },
            top_center_screen = {
                enable = true,
                offset = {
                    x = 0,
                    y = 0,
                },
            },
        },
    },
    eztargeting = {
        enable = true,
    },
    savedUI = {},
    saved_ui_info = {
        ui_res = {},
    },
    savedui = {},
}
